# Secrets for your Eventbrite app
#
# This file should never go into github!

export EVENTBRITE_TOKEN="LOLPSL6YRGRAHIWLLOQ5"
export EVENTBRITE_KEY="NK6NDHMEMW7JDZ6AVA"
export EVENTBRITE_SECRET="XL7D62X3WGYWZARWNPNMWR4COEBWPBGSNFWB462TGXXADENUG3"
